FROM golang:1.17

ENV DOCKER_VERSION=20.10.5

RUN curl -sL https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz -o docker-${DOCKER_VERSION}.tgz \
  && tar -zxvf docker-${DOCKER_VERSION}.tgz -C /usr/bin docker/docker --strip-components 1 \
  && chmod +x /usr/bin/docker

ENV PATH /go/bin:$PATH
ENV DAPPER_SOURCE /workspace
ENV DAPPER_OUTPUT bin build/bin dist
ENV DAPPER_DOCKER_SOCKET true
ENV DAPPER_ENV TAG REPO GOOS CROSS DRONE_TAG SHORT E2E_USE_EXISTING KUBECONFIG
ENV DAPPER_RUN_ARGS "-v opni-support-build-go17-pkg:/go/pkg -v opni-support-build-go17-cache:/root/.cache/go-build"
ENV GOCACHE /root/.cache/go-build
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["build"]