#!/bin/bash

cd $(dirname $0)

source version

cd ..

declare -A OS_ARCH_ARG

OS_PLATFORM_ARG=(linux darwin)
OS_ARCH_ARG[linux]="amd64 arm"
OS_ARCH_ARG[darwin]="amd64"

if [ -n "$CROSS" ]; then
    for OS in ${OS_PLATFORM_ARG[@]}; do
        for ARCH in ${OS_ARCH_ARG[${OS}]}; do
            OUTPUT_BIN="bin/opni-supportagent_$OS-$ARCH"

            echo "Building binary for $OS/$ARCH..."
            GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build \
                  -ldflags="-w -X main.VERSION=$VERSION" \
                  -o ${OUTPUT_BIN} .
        done
    done
else
    CGO_ENABLED=0 go build -ldflags="-w -s -X main.VERSION=$VERSION -extldflags -static" -o bin/opni-supportagent .
fi