on:
  push:
    tags:
    - 'v*'

name: Publish Release Artifact

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.46
  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: CROSS=1 scripts/build
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: thedoctor0/zip-release@main
      with:
        type: tar
        filename: opni-supportagent_${{ steps.get_version.outputs.VERSION }}.tar.gz
        directory: ./bin/
        path: .
        exclusions: opni-supportagent_${{ steps.get_version.outputs.VERSION }}.tar.gz
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/opni-supportagent_${{ steps.get_version.outputs.VERSION }}.tar.gz

  